### ISSUE TITLE
ThenBy for PHP

### ISSUE THREAD

**Issue by rentalhost** [Teun/thenBy.js#10]
Hello. I like of how thenBy() works and I like to reimplements it on a PHP. So I want to know if I can do it based on your concept. It should be called VanillaSort, because I'm working on a big package called Vanilla: https://bitbucket.org/rentalhost/

**Comment by Teun** [comment]
Well, feel free. However, the language constructs already available in
JavaScript and PHP are quite different. I think the code will not help you
much. The api design can be reused of course.
Op 6 okt. 2015 11:36 schreef "David Rodrigues" <notifications@github.com>:

**Comment by rentalhost** [comment]
I need do a lot adapt, but the concept is good for me, and maybe I can use it in someway. The php `array_multi_sort()` not is very clear for me. I should use your tests cases too.

Thanks a lot.

**Comment by rentalhost** [comment]
Very few adaptations: https://github.com/VanillaPackage/vanilla-sort/blob/master/src/VanillaSort/Sort.php

Well, source code is bigger than JS, but it is only a detail. :stuck_out_tongue:
