### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by glennjones** [Teun/thenBy.js#12]
Hi Like the library any chance you could add a licence to it, such as MIT or one of the other permissive licences. Makes it easier to use your code if your working on larger open source projects where licences of are tracked and monitored.

**Comment by Teun** [comment]
thenby.js is and has always been licensed under the Apache Public License 2.0. It is included at the top of the source code.

Is there a way you or others could easier discover this?

**Comment by Teun** [comment]
I've added a LICENSE.TXT to the root of the repo, indicating the Apache 2.0 license.
