### ISSUE TITLE
Official npm package

### ISSUE THREAD

**Issue by felixfbecker** [Teun/thenBy.js#13]
The fork https://www.npmjs.com/package/thenby is old and doesn't even have a `module.exports`. I really like this micro library and would like to use it. Could you publish it on npm? You could use `firstby-thenby` as name.

**Comment by felixfbecker** [comment]
I saw that your package.json has `name: "thenBy.js"` but I cant find that on npm.

**Comment by Teun** [comment]
I would like to use the existing npm package and point it to my original repo. I have actually tried to contact @rodriguezartav some six months ago, but never got a reply. I would prefer existing users of the npm module to be able to `npm update`. I don't care much about ownership or control, but it seems inproductive to have thenBy and thenBy.js side-by-side.

**Comment by felixfbecker** [comment]
I definitely agree, but his package is broken, it doesnt even export anything. At the moment, I include thenBy from NPM via direct git link, but this means I cannot npm update and also if this repo goes down I will not be able to install anymore, while NPM keeps legacy packages forever. If you contacted him six months ago, I guess it's safe to say he will not answer... You could try to contact npm to transfer ownership, but I dont think that will work. I know it sucks having forks in the npm registry, but it's the sad truth with NPM's model. Btw NPM recommends not to put .js in the name of the package since this is npm and it's assumed to be in javascript, and the naming convention is definitely kebab-case. So, since this modules name is thenBy in camelCase, the true npm name would actually be `then-by`. Please consider just publishing under that name. This module is great and I'm not very confident in linking to github for my dependencies.

**Comment by rodriguezartav** [comment]
Sorry I am lost, what do you need me to do?

**Comment by felixfbecker** [comment]
Transfer ownership of https://www.npmjs.com/package/thenby to Teun so he can update the package  :)

**Comment by rodriguezartav** [comment]
@Teun sorry about that and for missing your request. Is all clear for you to publish and manage your module.

**Comment by Teun** [comment]
Oh, wow, that awesome. What should I do to make this work? Just follow the guidance I now see on https://www.npmjs.com/package/thenby ?

**Comment by Teun** [comment]
And changing the name in my package.json to thenBy instead of thenBy.js?

**Comment by rodriguezartav** [comment]
Yes. I would do this:

1. Register/login to NPM ( if you have not )

2. Make sure name, version, repository, license and such are correct on package.json ( you can change everything but the name in the future )

3. npm publish

**Comment by Teun** [comment]
OK, I will do this later tonight. Thanks for your help. This is a major improvement for users of npm.

**Comment by felixfbecker** [comment]
@Teun but please use lowercase name (with dashes), that's the convention. So `then-by` or `thenby`, which ever you prefer.

This really is a major improvement.

**Comment by Teun** [comment]
Done. Looks good to me. Can you guys check that it is as intended?

**Comment by felixfbecker** [comment]
I can confirm that everything works :)
Thanks a lot (to you both) for resolving this so quick.
@Teun I think you should update the section in the readme on installing in Node.

Btw, this module works extremely well with [javascript-natural-sort](https://www.npmjs.com/package/javascript-natural-sort)

**Comment by Teun** [comment]
Done. Thanks al.
