### ISSUE TITLE
add a var delcaration ?

### ISSUE THREAD

**Issue by mh-cbon** [Teun/thenBy.js#20]
Hi,

at https://github.com/Teun/thenBy.js/blob/master/thenBy.js#L16 the firstBy is not declared with var.
This is a problem when using strict mode, it triggers an error

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Erreurs/Undeclared_var?utm_campaign=default&utm_medium=firefox-console-errors&utm_source=mozilla

thanks

**Comment by mh-cbon** [comment]
lets just wrap it with this umd https://github.com/eduardolundgren/gulp-umd

**Comment by Teun** [comment]
Yes, this looks like the way to go. I don't want to keep track of all the
favorite ways of loading and packaging forever.

I will implement this eventually, but maybe you can help and speed this up?

T

Op 28 nov. 2016 23:17 schreef "mh-cbon" <notifications@github.com>:
