### ISSUE TITLE
no way sort strings numerically

### ISSUE THREAD

**Issue by grkblood13** [Teun/thenBy.js#23]
It would be REALLY nice if there was a way to sort strings numerically instead of lexicographically. A stackoverflow post like the following shows how to do it with arrays. Could this be added?

https://stackoverflow.com/questions/8107226/how-to-sort-strings-in-javascript-numerically

**Comment by Teun** [comment]
Using the unary function sorting shortcut and the Number() function from javascript, you can easily achieve this:

    var values = ["2", "20", "03", "-2", "0", 200, "2"];
    var sorted = values.sort(firstBy(Number));

If you are sorting more complex objects with a string-typed number in one of the properties, it would look more like this:

    var values = [{a:"2"}, {a:"20"}, {a:"03"}, {a:"-2"}, {a:"0"}, {a:"200"}, {a:"2"}];
    var sorted = values.sort(firstBy(function(v){return Number(v.a)}));

**Comment by Teun** [comment]
I've added numeric sorting to the readme and tests.

**Comment by grkblood13** [comment]
So I tried the following and it didn't work. The problem isn't sorting strings that convert to numbers, its sorting strings with numbers in a numerical way.

var firstBy = require('./node_modules/thenby');
var ob = [{name:"a1b3"},{name:"a10b11"},{name:"b10b2"},{name:"a9b2"},{name:"a1b20"},{name:"a1c4"}];
var sorted = ob.sort(firstBy(function(v){return Number(v.name)}));
console.log(sorted);

actual output:
[ { name: 'a1b3' },
  { name: 'a10b11' },
  { name: 'b10b2' },
  { name: 'a9b2' },
  { name: 'a1b20' },
  { name: 'a1c4' } ]

expected output:
[ { name: 'a1b3' },
  { name: 'a1b20' },
  { name: 'a1c4' },
  { name: 'a9b2' } ,
  { name: 'a10b11' },
  { name: 'b10b2' }]

expected out

**Comment by Teun** [comment]
Eh. And why would that be the expected output? I see that your strings contain numerals, but I have no idea why you have ordered them like this.

Bottom line: if you can write a function that converts your data to something that can be sorted, you can pass in that function. Whatever the logic you see in these strings, I don't think it should be a standard feature of thenBy.
