### ISSUE TITLE
Make this library ES6 + TypeScript compliant?

### ISSUE THREAD

**Issue by jsgoupil** [Teun/thenBy.js#26]
It would be interesting to see this library ES6 compliant and working with TypeScript.

That's a beginning of a declaration:

    interface ThenBy {
        thenBy(fnc: ((v1, v2) => number) | string, direction?: number): ThenBy;
        thenBy(propertyName: string, direction?: number): ThenBy;
        (fnc: (v1, v2) => number);
    }

    function firstBy<T>(fnc: (v1: T, v2: T) => number, direction ?: number): ThenBy;
    function firstBy<T>(propertyName: keyof T, direction ?: number): ThenBy;

**Comment by Teun** [comment]
Starting work on this. Have used typescript before, but never created bindings myself. Need some investigation...

**Comment by Teun** [comment]
JS,
I just published v. 1.2.4 to npm. Could you test if this type declaration works for you like this? Because of how type inference works, you'll have to specify the type on the first call to firstBy, like this:

```
class User {
    name: string;
    length: number;
}
let items: User[] = [
    {name: "Tony", length: 167},
    {name: "Elsa", length: 159},
    {name: "Bert", length: 192},
];

console.log(items.sort(
    firstBy<User>((a, b) => a.length - b.length)
      .thenBy(v => v.name.length)
      .thenBy("name")
));
```

**Comment by Teun** [comment]
Made the default type of T be `any` for firstBy. That should make the usages of calls without any type be valid.

**Comment by jsgoupil** [comment]
@Teun  Sorry I have been on vacation for 45 days. I will give a shot soon and report if any problems. Thanks!

**Comment by Teun** [comment]
Ah, that's awesome.

Op ma 11 jun. 2018 16:38 schreef Jean-Sébastien Goupil <
notifications@github.com>:

**Comment by Teun** [comment]
In https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html the example that seems of relevance goes like: 

```
/*~ This declaration specifies that the function
 *~ is the exported object from the file
 */
export = MyFunction;
```

**Comment by HonoluluHenk** [comment]
Did some research, too:

Using the suggested method:
``import firstBy = require('thenby');``
... fails with:
``error TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.``

So it seems like Typescript cannot (yet?) handle this well.
The simplest change to make it work would be to replace
``export = firstBy``
with
``export default firstBy``
See: https://www.typescriptlang.org/docs/handbook/modules.html (section "Default exports").

In my source I can then use the TS import syntax for default exports:
``import firstBy from 'thenby';``
and everythin works as expected.

Added bonus of this change: importing via require('thenby') should still work.

**Comment by HonoluluHenk** [comment]
Addendum: using any of the other import methods suggested by the TS1202 error message fails with various TS compiler errors

**Comment by Teun** [comment]
Awesome. Thanks for your work, Christoph. I will try it out and apply this
change if it works for me.
One question: which version of typescript do you use?

Teun

Op za 30 jun. 2018 01:53 schreef Christoph Linder <notifications@github.com

**Comment by HonoluluHenk** [comment]
Don't have access to a computer right now :unamused:
My testcase yesterday was a fresh angular app.
See here: https://cli.angular.io/

**Comment by Teun** [comment]
I guess the problem is the ES6 style module importing expects the module to export an object (bunch of properties), not a callable function or a class Constructor. So, to allow for ES6 style importing, I have changed the module a little bit. It now exports a function **with a firstBy property on it**. So you can still use it in the  old way using require(), but you can now also do (this is the recommended way for TypeScript now):
```javascript
import (firstBy) from "thenby";
```
Pushed as version 1.2.6. Please test for your scenario.

**Comment by HonoluluHenk** [comment]
The new version works, thank you for fixing this so fast!
