### ISSUE TITLE
Could you explain how to use it with TS in a more detailed way?

### ISSUE THREAD

**Issue by maxhalper** [Teun/thenBy.js#29]
Please explain how to call it with Typescript in a more detailed way.

What i have tried:
I have added the files to my project and made the import statement.
import {firstBy} from "thenby"; 

How do i instantiate it/ call it now? I always get an undefined for firstBy. I have tried multiple ways but none of them worked. 

An example would be great.

Thank you in advance. Great work!

**Comment by Teun** [comment]
I have recorded a quick demo. Of course, the experience depends heavily on your IDE. This was recorded with VS Code. Hope this helps you...
https://youtu.be/atJPa3AE4bM
