### ISSUE TITLE
Sorting an array of Id's based on Objects (with id)

### ISSUE THREAD

**Issue by CallumHemsley** [Teun/thenBy.js#30]
So I'm using redux, and in my store I store the rows of my table like this: 

```js
jobs: {
    byJobId: {}, //Objects indexed by id
    allJobIds: [] //Array of ids to indicate sorting order
  },
```

Is it possible to use this library to sort the array based on the object via its id?

**Comment by CallumHemsley** [comment]
Right now, I'm sorting for one column at a time like this:
```js
jobs.allJobIds.sort(function(a, b) {
    return(jobs.byJobId[a]["id"] - jobs.byJobId[b]["id"] 
  })
```

**Comment by Teun** [comment]
Let's see if I follow you. You want to have a sorted list of the IDs in `allJobIds`, but not on the ID itself, but some property of the object in the `byJobId` dictionary object? Like this:
``` javascript
    jobs.allJobIds.sort(
      firstBy(id => jobs.byJobId[id].name)
        .thenBy(id => jobs.byJobId[id].id)
    );
```

**Comment by CallumHemsley** [comment]
Yep you're following. That's exactly what I want. Brilliant, thank you!

I have one follow up question, in that I want to make this dynamic.

What I mean by that I'll have an obj with the sortkeys + direction like so:
```js
const sortKeysWithDirection = { name: -1, id: 1};
```
From this I want to be able to use the .thenBy() for as many extra sortKeys are provided. I've managed to do something like this without the lib like so:
```js
jobs.allJobIds.sort(function(a, b) {
    for(const [key, dir] of Object.entries(sortKeysWithDirection)) {
      let bigger, smaller;
      bigger = (dir === "desc") ? -1 : 1;
      smaller = (dir === "desc") ? 1 : -1;
      if (jobs.byJobId[a][0][key].value > jobs.byJobId[b][0][key].value) return bigger;
      if (jobs.byJobId[a][0][key].value < jobs.byJobId[b][0][key].value) return smaller;
    }
  })
```

Once again, thanks for the fast reply, and the awesome library!

**Comment by CallumHemsley** [comment]
Closing this as I solved using Lodash. Thanks for your hard work.

**Comment by Teun** [comment]
If lodash floats your boat, that cool. For later reference, let me answer your last question here anyway, as it may be useful to others later.

If you want to dynamically create the sorter function, you can, but you must make sure that you append then to each other in the right order. I had to change your `sortKeysWithDirection` a bit. Keys in a javascript object have no order. Order is the whole point here, so that will not work. Would be something like this:

```javascript
const sortKeysWithDirection = [ {prop: "name", "dir": 1} { prop: "id", "dir": -1} ];
let ordering = firstBy(k => 1); //dummy order
sortKeysWithDirection.forEach(o => {
  ordering = ordering.thenBy(id => jobs.byJobId[id][o.prop], o.dir);
});
jobs.allJobIds.sort(ordering);
```

Haven't actually tested this code, so forgive me for syntax.

**Comment by praveenupadhyay997** [comment]
Hi @Teun, I also am looking for similar problem. I have total 21 columns in a table. But it has at a time only 100 rows. I was chaining multiple thenBy 's passing a parameter 

properties.sort.firstBy(field: string, order: number (1 or -1)).thenBy(field: string, order: number (1 or -1))...... multiple thenBy's

By these thenBy's are not doing their function. Am I missing anything

**Comment by Teun** [comment]
Hi @praveenupadhyay997, 
Of course I can have a look at your problem. Please open a new issue and provide me an example of the problem. Preferable with an example of your data and a snippet of the code.
