### ISSUE TITLE
global usage in Vue

### ISSUE THREAD

**Issue by knot22** [Teun/thenBy.js#31]
I have been able to successfully use the thenBy library in a Vue file like so -
Official Scenarios Vue file:
```
<template>
    <div>
        {{ sortedOfficialScenarios }}
    </div>
</template>

<script>
import { firstBy } from 'thenby';

export default {
     data () {
         return {
             officialScenarios: []
         }
     },
     methods: {
         async getOfficialScenarios() {           
            this.officialScenarios = await this.$service.access('officialScenarios').get();
         }
     },
     created: function () {
         this.getOfficialScenarios();
     },
     computed: {
         sortedOfficialScenarios() {
             return (this.officialScenarios).slice().sort(
                 firstBy(function (a) { return a.year }, -1)
                 .thenBy('created', -1)
            );
         }
     }
}
</script>
```
thenBy is a useful library for this project so I'd like to include it globally to avoid having import statements in each Vue file.  However, this is where I'm stuck.  In main.js I've tried:
```
import { firstBy } from 'thenby';
Vue.use(firstBy);
```
With that code in place, and the `import { firstBy} from 'thenby';` disabled in the Official Scenarios file, an error is displayed in the console that says _Error in render: "ReferenceError: firstBy is not defined"_.  I have also tried this in main.js:
```
import { firstBy } from 'thenby';
new Vue({
  router,
  firstBy,
  render: h => h(App)
  }
}).$mount('#app');
```
The error message is the same as above.

Is there a way to use thenBy globally in Vue?  If so, how?

**Comment by Teun** [comment]
I have little knowledge of Vue and how to import external libraries in it. Thenby is not very special as an external module. You can import it in the normal TypeScript or ES6 way. Maybe you should ask this in a Vue forum.

**Comment by Teun** [comment]
If I do not hear back, I will soon close this issue, as it should be easy to use any javascript module inside Vue.
