### ISSUE TITLE
Typings improvement

### ISSUE THREAD

**Issue by HonoluluHenk** [Teun/thenBy.js#32]
With typescript (v3.8.3), the compiler tells me that the second parameter of the key-param on firstBy/thenBy (i.e.: "v2") might be undefined... which just isn't true if using the `(a,b)=> number` form.

Imho these typings should provide a better user-experience while stille sticking to your spec:

```
  export function firstBy<T = any>(key: ((v1: T, v2: T) => any), direction?: number | opt): IThenBy<T>;
  export function firstBy<T = any>(key: ((v1: T) => any), direction?: number | opt): IThenBy<T>;
  export function firstBy<T = any>(key: (keyof T), direction?: number | opt): IThenBy<T>;
  // catch all implementation. Might perhaps be omitted for clarity.
  export function firstBy<T = any>(key: ((v1: T, v2?: T) => any) | keyof T, direction?: number | opt): IThenBy<T>;

```

**Comment by Teun** [comment]
That sounds like a great improvement. Thank you. I will look into it in detail tomorrow.

**Comment by Teun** [comment]
I have created a pull request for this issue. I have tested it and it seems to work like a charm. If you want to have a look: please do. I will merge later this weekend, unless you see anything that could be improved.

**Comment by Teun** [comment]
By the way: thanks a lot for your contribution. I never knew that you can define function overloads in this way. I have also taken the opportunity to include more comments and make the typing of the direction parameter more strict.

**Comment by HonoluluHenk** [comment]
Hi Teun, thanks for the fast reply!

Imho, the "T = any" could be reduced to just "T" since T is always inferred by the compiler/IDE.

For the "simple property" overload I'd write:
`firstBy<T extends object>`
Since extracting properties probably only makes sense for objects but not numbers, strings, ....

Since you mentioned direction: see PR #34 :)

**Comment by Teun** [comment]
Limiting by "extends object" would exclude String.length. Not sure What advantage it would give. What _would_ be very nice would be limiting to keys that are a property, not a method. But I don't htink that is something typeScript can specify. I will remove the superfluous "= any".

**Comment by HonoluluHenk** [comment]
Thanks, you rock!
