### ISSUE TITLE
Github Releases?

### ISSUE THREAD

**Issue by nileshpatra** [Teun/thenBy.js#38]
I wish to use this in a project - hence I wanted this to be tagged.

**Comment by nileshpatra** [comment]
@Teun can yo do the needful?

**Comment by nileshpatra** [comment]
Although the package.json says; version": "1.3.3
There's not g/h release. 
Can you please do this in accordance with the package.json?

**Comment by Teun** [comment]
ThenBy is released through npm. https://www.npmjs.com/package/thenby
