### ISSUE TITLE
license in package.json not according to SPDX

### ISSUE THREAD

**Issue by HonoluluHenk** [Teun/thenBy.js#39]
There's a more or less official list of license names/abbreviations: https://spdx.org/licenses/
This list ist used by some tools (e.g.: [license-checker](https://github.com/davglass/license-checker)) to do some useful stuff.

I propose changing the "license" entry in package.json from "Apache 2.0" to "Apache-2.0" according to SPDX.

**Comment by Teun** [comment]
Interesting. Wasn't aware of that. I will update it.

**Comment by HonoluluHenk** [comment]
Thanks!
Care to release?

**Comment by Teun** [comment]
Does it need a release to become effective? I assumed that tools woud check the master branch of projects.

**Comment by Teun** [comment]
Done

**Comment by HonoluluHenk** [comment]
Most tools only check the versions installed locally (i.e. by `npm install`).

Thanks for your swift response, btw!
