### ISSUE TITLE
Sorting does not work

### ISSUE THREAD

**Issue by tqdo** [Teun/thenBy.js#42]
Hi, maybe I am missing something but I could not get my array to sort using the example you provided. I also saw the fiddle you posted on a stackoverflow answer but the result over there is also not sorted (http://jsfiddle.net/n4ncq2nc/1/). Thanks

**Comment by Teun** [comment]
Yes, you are missing something. This is your code:

``` javascript
var x = v.sort(
    firstBy(function (v1, v2) { return v1.is_online - v2.is_online; })
    .thenBy(function (v1, v2) { return v1.name - v2.name; })
);
```
You are using a veeeery old version of thenBy in this snippet. Later versions would make the kind of sort you are trying to do here much easier (see below). But this old version should also work. Problem is that the functions you pass here should return 0 if both values are to be sorted equally, a positive number when the first is larger and a negative number when the second is larger. For a number typed property, you can achieve this by subtracting (as you do here with is_online), but for strings this will not work. The result of "raul" - "suresh" is not a numeric value, but NaN. You can fix it by doing this:

``` javascript
var x = v.sort(
    firstBy(function (v1, v2) { return v1.is_online - v2.is_online; })
    .thenBy(function (v1, v2) { return v1.name > v2.name ? 1 : -1; })
);
```
But even easier, if you use a more recent version of thenBy, you could just have done: 
``` javascript
var x = v.sort(
    firstBy("is_online")
    .thenBy("name")
);
```
