### ISSUE TITLE
It doesn't work after firstBy

### ISSUE THREAD

**Issue by biznisprofil** [Teun/thenBy.js#44]
Hi I cannot make it work after the first condition.
`
this.itemsCollection.sort(
      
 firstBy(function(a: ItemDto, b: ItemDto) {
        console.log('first')
        return a.title.length - b.title.length
      })
       
  .thenBy(function(a: ItemDto, b: ItemDto) {
          console.log('second')
          return a.text.length - b.text.length
        })
        
 .thenBy(function(a: ItemDto, b: ItemDto) {
          console.log('third')
          return a.itemId - b.itemId
        })
    
)
`
It works well for the first block but not for the others. What I am doing wrong? Thanks
![image](https://user-images.githubusercontent.com/14800646/106267768-6a823a00-622a-11eb-85c4-e02a980869f7.png)

**Comment by Teun** [comment]
I cannot see your actual data very well here. If the items in your test set have different lengths of titles, then this behavior is correct. The seond step only runs when two items have the same sort order after the first step. So it first evaluates step 1. If it returns <0 or >0 the sorting is done. Only when it returns exactly 0, the second and maybe third step are invoked.

Does that make sense or would you still expect your second and third steps to be invoked?

**Comment by biznisprofil** [comment]
Ok, Thanks for your replay. firstBy works correctly, but I am expecting to have all conditions invoked. For example is it possible to first check if conditions is true, sort to the top. Then Sort by date. Some of the objects will have it true some of them, will have it false. I can make it with this condition 
return a.isPriority > b.isPriority ? -1 : 1
// it won't return 0
but they won't have same just one condition.

**Comment by Teun** [comment]
I'm not sure that I understand you. Can you make an example where the sorting is wrong? You can use this fiddle as a starting point: http://jsfiddle.net/cnwg5Lky/

**Comment by biznisprofil** [comment]
Thanks for your trouble. So here is what I am trying to do: 

1. Sort by "isPriority" (true first, false second)

2. Than sort by "dueDate":
  - First items with non-NULL due date (descending: newer first, older later)

3. Then items with NULL due date
  - Sort items with NULL due date by "createTime" (descending: newer first, older later)
  
And here is the fiddle implementation: 

http://jsfiddle.net/rswec30h/3/

**Comment by Teun** [comment]
Thank you. Now I get what you're after. The NULL sorting last is your trouble. In thenBy I would do it like this (working sample: http://jsfiddle.net/xamdtwL3/):

``` javascript
v.sort(
    firstBy( a => a.isPriority, {direction: "desc"})
    .thenBy( a => a.dueDate || "9999")
    .thenBy( a => a.createTime)
);
``` 
I used the form with only one parameter per lambda function here. Generally, this is much easier to read and write. We first sort on `isPriority` and use the `desc` direction, because `false` sorts before `true`. Then we do the sorting by `dueDate`. Note how the `||` operator allows you to insert a fake value for the `null`s. In javascript the || operator is also called the "default". Then finally we sort by `createTime`.

**Comment by Teun** [comment]
By the way, the strange unpredictable behavior you an get when you leave the `null` in place is caused by the fact that in javascript:

``` javascript\
console.log("abc" < null); // prints false
console.log(null < "abc"); // prints false too
``` 
This will cause the sorting with null values to be strange. Maybe thenBy should do a null check and always sort null values last, but I'm not sure if that is always better. It would change the behavior.

**Comment by biznisprofil** [comment]
> Thank you. Now I get what you're after. The NULL sorting last is your trouble. In thenBy I would do it like this (working sample: http://jsfiddle.net/xamdtwL3/):
> 
> ```js
> v.sort(
>     firstBy( a => a.isPriority, {direction: "desc"})
>     .thenBy( a => a.dueDate || "9999")
>     .thenBy( a => a.createTime)
> );
> ```
> 
> I used the form with only one parameter per lambda function here. Generally, this is much easier to read and write. We first sort on `isPriority` and use the `desc` direction, because `false` sorts before `true`. Then we do the sorting by `dueDate`. Note how the `||` operator allows you to insert a fake value for the `null`s. In javascript the || operator is also called the "default". Then finally we sort by `createTime`.

Thanks for your implementation. This seems to be working. I wasn't aware for all possibilities of the lib. It simplify the code a lot. Thanks.

**Comment by Teun** [comment]
One more comment: if you feel that the `|| "9999"` is an ugly hack (point taken 😄 ), then you could also do this and follow the wording you used in your requirement description much more closely:

``` javascript
v.sort(
    firstBy( a => a.isPriority, {direction: "desc"})
    .thenBy( a => a.dueDate === null)
    .thenBy( a => a.dueDate)
    .thenBy( a => a.createTime)
);
```

**Comment by biznisprofil** [comment]
> One more comment: if you feel that the `|| "9999"` is an ugly hack (point taken 😄 ), then you could also do this and follow the wording you used in your requirement description much more closely:
> 
> ```js
> v.sort(
>     firstBy( a => a.isPriority, {direction: "desc"})
>     .thenBy( a => a.dueDate === null)
>     .thenBy( a => a.dueDate)
>     .thenBy( a => a.createTime)
> );
> ```

Now it looks even better. It actually resolve my second scenario, opposite direction for dueDate. 
`
this.itemsCollection.sort(
      firstBy((a: ItemDto) => a.isPriority, { direction: 'desc' })
        .thenBy((a: ItemDto) => a.dueDate === null)
        .thenBy((a: ItemDto) => a.dueDate, { direction: 'desc' })
        .thenBy(a => a.createTime, { direction: 'asc' })
    )
`
Thanks a lot! 👍
