### ISSUE TITLE
Could thenBy be attached to module.exports rather than the global scope?

### ISSUE THREAD

**Issue by ben-eb** [Teun/thenBy.js#5]
This is more to do with the [node fork](https://github.com/rodriguezartav/thenBy.js) but there's no issue tracker...

ping @rodriguezartav

**Comment by Teun** [comment]
Sure could. If we turn it into a Common.JS module, would it be easy to still use it in a straigh-forward way for browser developers that use no loader/require system?

**Comment by Teun** [comment]
I see that @killercup has created a Common.JS version in his fork: https://github.com/killercup/thenBy.js

**Comment by ben-eb** [comment]
Yup, it would be possible to fallback to a window global:

```js
var isCommonjs = typeof module !== 'undefined' && module.exports;

if (isCommonjs) {
  module.exports = firstBy;
} else {
  window.firstBy = firstBy;
}
```

**Comment by Teun** [comment]
I wanted not to include too much extra stuff in the plain javascript version, so I checked in a separate version for CommonJS/node.js use. It is called thenBy.module.js. I've also added a package.json for including the code via npm.

**Comment by ben-eb** [comment]
:+1:
