### ISSUE TITLE
Number Ordering

### ISSUE THREAD

**Issue by lawrencenull** [Teun/thenBy.js#52]
Thank you for this library, I've been using it quite a bit. Came across a sorting problem when sorting number values above 2 digits, it sorts 99 and below first only taking into account the first digit. Below is an example ordered ascending, it goes 10, 100, 101, etc for ordering.

https://jsfiddle.net/lawrencenull/xL5pc2dw/1/

**Comment by Teun** [comment]
Thanks for reporting, so I can help you out and maybe others can find this. 

Your example is rather long, but the essence is this:
``` javascript
var results = [
{
  "id": "Q30",
  "itemLabel": "United States of America",
  "sl": "20",
}, {
  "id": "Q159",
  "itemLabel": "Russia",
  "sl": "100",
}
];
var s = firstBy("sl", "asc");
results.sort(s);
```
Note how your JSON data has `sl` properties, but this property is of type String (it has quotes around it). Without any further specification, strings are sorted alphabetically, so "100" comes before "20". If the JSON would have no quotes around the value (`"sl": 20`), the sorting would be as you expect.

If you have no way of making the data numeric, you can do the conversion as part of the sorting. Like this: 
``` javascript
var s = firstBy((item) => Number(item.sl), "asc");
results.sort(s);
```
