### ISSUE TITLE
Provide a es6 version?

### ISSUE THREAD

**Issue by rowild** [Teun/thenBy.js#55]
I tried to rewrite your wonderful script as a es6 module (`export thenBy ...` and `import thenBy from ...`), but I fail shamefully. So I wonder if there is a chance to motivate you to provide a script that follows that convention?

**Comment by rowild** [comment]
Hmmm... I did use the function that you use in your sample.html, maybe that's enough?

```js
// src/helper/thenBy.js
const firstBy = (function () {
   [...]
}

export default firstBy

/// src/Index.vue
import firstBy from '.../helper/thenBy.js'
```

Not the most elegant solution, but it works.

**Comment by Teun** [comment]
Frankly, I have been struggling quite a bit getting this supported and keeping the code backward compatible. Did the import line you show work for you? It you install the module using npm or yarn, I think this should just work.

**Comment by rowild** [comment]
There is a npm module??? Bite me - why didn't I think of that? Shame on me! :-(

The import as I show it works, but I have no idea if it is "good" that way. The IIFE's the code uses are beyond my understanding. I search stackoverflow for advices on how to convert an IFFE to a ES6 module and found this:
https://stackoverflow.com/questions/61883135/exporting-iife-formated-function-to-es6-module

But some people there say that the recommended solution is really not recommendable (there is a link in a comment).

I will try the npm version of course! Sorry that I missed to check that source – it is really so obvious to do that, I wonder why I didn't...
