### ISSUE TITLE
Group Sorting

### ISSUE THREAD

**Issue by aHumanBeing** [Teun/thenBy.js#7]
Hi,  

Been using thenBy for a few weeks now and I like it alot.  It simply works.  I'm in a bit of a stump though trying to figure out if a specific sort is possible with this module.

I have records displayed in a table which have attributes: priority of 0 - 2 (2 being most important), person status of 0 - 4, wait time, and total time.

I'm trying to sort this information (in tiers if you will) like so:
- tier 1: priority 2 records are always at the top sorted by wait time then total time
- tier 2: priority != 2 and person status != 0 records sorted by wait time
- tier 3: priority != 2 and patient status = 0 records sorted by total time

No biggie if this isn't possible.  Just curious.  Thanks!

**Comment by Teun** [comment]
Well, technically, thenBy could be part of your solution. In the end it is
only a trick for combining multiple functions. The first could be a
function returning (priority === 2) and a second function could deal with
the order after that. But frankly, I think you're better off just coding 1
function taking care of the whole order
I would advise against a solution where you combine filtering and sorting,
as that would introduce the risk of having duplicate or disappearing items.
Op 30 jul. 2015 20:28 schreef "aHumanBeing" <notifications@github.com>:

**Comment by aHumanBeing** [comment]
Totally understand what you're saying.  Thanks for the quick feedback as well!
